config/routes.rb
Extract::Application.routes.draw do
  
  get '/import'  => "import#index"
  post '/import' => "import#import"
  
  resources :activities
  
  devise_for :users
  
  root :to => "application#index"
  
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  
  before_save :set_slope
  before_save :set_average_speed
  
  private
  def set_slope
    unless total_elevation_gain.blank? || distance.blank?
      self.slope = BigDecimal.new(sprintf( "%.2f", (total_elevation_gain.to_f / (5280 * distance.to_f)) * 100 * 2))
    end
  end
  
  def set_average_speed
    unless distance.blank? || duration.blank?
      self.average_speed = BigDecimal.new(sprintf( "%.2f", (distance.to_f / duration.to_f) * 3600,2))
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :current_user_owns_activity?, :only => [:show, :edit, :update, :destroy]
  
  # GET /activities
  # GET /activities.xml
  def index
    @activities = Activity.
                    find_all_by_user_id(current_user.id, :order => params[:order_by]).
                    paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.xml
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.xml
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @activity }
    end
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.xml
  def create
    @activity = Activity.new(params[:activity])
    @activity.user = current_user
    
    respond_to do |format|
      if @activity.save
        format.html { redirect_to(@activity, :notice => 'Activity was successfully created.') }
        format.xml  { render :xml => @activity, :status => :created, :location => @activity }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.xml
  def update
    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to(@activity, :notice => 'Activity was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.xml
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to(activities_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def current_user_owns_activity?
    @activity = Activity.find(params[:id])
    if @activity.user != current_user
      flash[:alert] = "You don't have access to that Activity!"
      redirect_to :root
    end
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index
  end

end

app/controllers/import_controller.rb
class ImportController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :user_signed_in?
  
  def index
  end
  
  def import
    if request.post?
      unless params[:csv].path.empty?
        Activity.destroy_all(:user_id => current_user.id)
        FasterCSV.foreach(params[:csv].path, :headers => :first_row, :skip_blanks => true) do |row|
          record = row.to_hash.merge(:user => current_user)
          if record["duration"].present?
            record["duration"] = ActiveSupport::Duration.parse(record["duration"])
          end
          Activity.create(record)
        end
        flash[:notice] = "CSV File Imported"
      end
    end
    
    redirect_to :root
  end
  
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def order_by_links(path_function, name)
    link_to("^", send(path_function, :order_by=>"#{name}")) + " " + link_to("v", send(path_function, :order_by=>"#{name} desc"))
  end
  
  def format_duration(integer)
    if integer.present?
      hours = integer / (60 * 60)
      minutes = (integer - (hours * 60 * 60)) / 60
      seconds = (integer - (hours * 60 * 60) - (minutes * 60))
      return "#{hours}:#{minutes}:#{seconds}"
    end
  end
  
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br />
    <%= f.date_select :day %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :activity %><br />
    <%= f.text_field :activity %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br />
    <%= f.text_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :equipment %><br />
    <%= f.text_field :equipment %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :distance %><br />
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :max_speed %><br />
    <%= f.text_field :max_speed %>
  </div>
  <div class="field">
    <%= f.label :average_heart_rate %><br />
    <%= f.text_field :average_heart_rate %>
  </div>
  <div class="field">
    <%= f.label :max_heart_rate %><br />
    <%= f.text_field :max_heart_rate %>
  </div>
  <div class="field">
    <%= f.label :calories %><br />
    <%= f.text_field :calories %>
  </div>
  <div class="field">
    <%= f.label :max_elevation %><br />
    <%= f.text_field :max_elevation %>
  </div>
  <div class="field">
    <%= f.label :total_elevation_gain %><br />
    <%= f.text_field :total_elevation_gain %>
  </div>
  <div class="field">
    <%= f.label :total_elevation_loss %><br />
    <%= f.text_field :total_elevation_loss %>
  </div>
  <div class="field">
    <%= f.label :with %><br />
    <%= f.text_area :with %>
  </div>
  <div class="field">
    <%= f.label :average_cadence %><br />
    <%= f.text_field :average_cadence %>
  </div>
  <div class="field">
    <%= f.label :route %><br />
    <%= f.text_area :route %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_area :link %>
  </div>
  <div class="field">
    <%= f.label :weather %><br />
    <%= f.text_area :weather %>
  </div>
  <div class="field">
    <%= f.label :how_i_felt %><br />
    <%= f.text_field :how_i_felt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<%= will_paginate(@activities) %>

<table>
  <tr>
    <th>Day <%= order_by_links("activities_path","day") %></th>
    <th>Time <%= order_by_links("activities_path","time") %></th>
    <th>Activity <%= order_by_links("activities_path","activity") %></th>
    <th>Location <%= order_by_links("activities_path","location") %></th>
    <th>Temperature <%= order_by_links("activities_path","temperature") %></th>
    <th>Equipment <%= order_by_links("activities_path","equipment") %></th>
    <th>Duration <%= order_by_links("activities_path","duration") %></th>
    <th>Distance <%= order_by_links("activities_path","distance") %></th>
    <th>Average speed <%= order_by_links("activities_path","average_speed") %></th>
    <th>Max speed <%= order_by_links("activities_path","max_speed") %></th>
    <th>Average heart rate <%= order_by_links("activities_path","average_heart_rate") %></th>
    <th>Max heart rate <%= order_by_links("activities_path","max_heart_rate") %></th>
    <th>Calories <%= order_by_links("activities_path","calories") %></th>
    <th>Max elevation <%= order_by_links("activities_path","max_elevation") %></th>
    <th>Total elevation gain <%= order_by_links("activities_path","total_elevation_gain") %></th>
    <th>Total elevation loss <%= order_by_links("activities_path","total_elevation_loss") %></th>
    <th>Slope <%= order_by_links("activities_path", "slope") %></th>
    <th>With <%= order_by_links("activities_path","with") %></th>
    <th>Average cadence <%= order_by_links("activities_path","average_cadence") %></th>
    <th>Route <%= order_by_links("activities_path","activity.route") %></th>
    <th>Notes <%= order_by_links("activities_path","notes") %></th>
    <th>Link <%= order_by_links("activities_path","link") %></th>
    <th>Weather <%= order_by_links("activities_path","weather") %></th>
    <th>How i felt <%= order_by_links("activities_path","how_i_felt") %></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.day %></td>
    <td><%= activity.time %></td>
    <td><%= activity.activity %></td>
    <td><%= activity.location %></td>
    <td><%= activity.temperature %></td>
    <td><%= activity.equipment %></td>
    <td><%= format_duration(activity.duration) %></td>
    <td><%= activity.distance %></td>
    <td><%= activity.average_speed %></td>
    <td><%= activity.max_speed %></td>
    <td><%= activity.average_heart_rate %></td>
    <td><%= activity.max_heart_rate %></td>
    <td><%= activity.calories %></td>
    <td><%= activity.max_elevation %></td>
    <td><%= activity.total_elevation_gain %></td>
    <td><%= activity.total_elevation_loss %></td>
    <td><%= activity.slope %></td>
    <td><%= activity.with %></td>
    <td><%= activity.average_cadence %></td>
    <td><%= link_to 'click', activity.route %></td>
    <td><%= activity.notes %></td>
    <td><%= activity.link %></td>
    <td><%= activity.weather %></td>
    <td><%= activity.how_i_felt %></td>
    <td>
      <%= link_to 'Show', activity %>
      <%= link_to 'Edit', edit_activity_path(activity) %>
      <%= link_to 'Destroy', activity, :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= will_paginate(@activities) %>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Day:</b>
  <%= @activity.day %>
</p>

<p>
  <b>Time:</b>
  <%= @activity.time %>
</p>

<p>
  <b>Location:</b>
  <%= @activity.location %>
</p>

<p>
  <b>Temperature:</b>
  <%= @activity.temperature %>
</p>

<p>
  <b>Equipment:</b>
  <%= @activity.equipment %>
</p>

<p>
  <b>Duration:</b>
  <%= format_duration(@activity.duration) %>
</p>

<p>
  <b>Distance:</b>
  <%= @activity.distance %>
</p>

<p>
  <b>Average speed:</b>
  <%= @activity.max_speed %>
</p>

<p>
  <b>Max speed:</b>
  <%= @activity.max_speed %>
</p>

<p>
  <b>Average heart rate:</b>
  <%= @activity.average_heart_rate %>
</p>

<p>
  <b>Max heart rate:</b>
  <%= @activity.max_heart_rate %>
</p>

<p>
  <b>Calories:</b>
  <%= @activity.calories %>
</p>

<p>
  <b>Max elevation:</b>
  <%= @activity.max_elevation %>
</p>

<p>
  <b>Total elevation gain:</b>
  <%= @activity.total_elevation_gain %>
</p>

<p>
  <b>Total elevation loss:</b>
  <%= @activity.total_elevation_loss %>
</p>

<p>
  <b>Slope:</b>
  <%= @activity.slope %>
</p>

<p>
  <b>With:</b>
  <%= @activity.with %>
</p>

<p>
  <b>Average cadence:</b>
  <%= @activity.average_cadence %>
</p>

<p>
  <b>Route:</b>
  <%= @activity.route %>
</p>

<p>
  <b>Notes:</b>
  <%= @activity.notes %>
</p>

<p>
  <b>Link:</b>
  <%= @activity.link %>
</p>

<p>
  <b>Weather:</b>
  <%= @activity.weather %>
</p>

<p>
  <b>How i felt:</b>
  <%= @activity.how_i_felt %>
</p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/application/index.html.erb
<h2>Hello!</h2>

app/views/import/index.html.erb
<h2>Import CSV</h2>

<%= form_tag import_path, :multipart => true do %>
    <label for="csv">CSV File:</label>
    <%= file_field_tag :csv %><br>
    <%= submit_tag "Upload", :disable_with => 'Uploading...' %>
<% end %>


<h2>Import KML</h2>
<em>Coming Soon!</em>

app/views/layouts/_account_links.html.erb
<ul>
  <% if user_signed_in? %>
    <li><%= link_to "Sign out", destroy_user_session_path %></li>
    <li><%= link_to "My Account", edit_registration_path('user') %></li>
    <li><%= link_to "My Activities", activities_path %></li>
    <li><%= link_to "Import...", import_path %></li>
  <% else %>
    <li><%= link_to "Sign in", new_session_path('user') %></li>
    <li><%= link_to "Sign up", new_registration_path('user') %></li>
    <li><%= link_to "Forgot your password?", new_password_path('user') %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>Extract</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<%= render :partial => 'layouts/account_links' %>
<hr />
<% if notice || alert %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<% end %>
<h1>Extract</h1>

<%= yield %>

</body>
</html>